[green_agent]
agentbeats_id = "019b8cfa-ed9a-7701-974a-65a5c7b238fb"
env = { AZURE_OPENAI_API_KEY = "${AZURE_OPENAI_API_KEY}", AZURE_OPENAI_ENDPOINT = "${AZURE_OPENAI_ENDPOINT}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = "019b8dca-139f-7971-b753-5070f4422d4a"
name = "Enterprise Purple Agent"
env = { AZURE_OPENAI_API_KEY = "${AZURE_OPENAI_API_KEY}", AZURE_OPENAI_ENDPOINT = "${AZURE_OPENAI_ENDPOINT}", LOG_LEVEL = "INFO" }


[config]
tasks_file = "tasks.json"
max_steps = 15
mcp_config_path = "./mcp_configs_http.json"

# Timeout for the entire assessment (in seconds)
timeout = 1800  # 30 minutes
